### ISSUE TITLE
 We could also host this webpage in github pages ?

### ISSUE THREAD

**Issue by MubarakNative** [jothi-prasath/movie-radar#8]
Now it is currently local host we can use github pages to host this webpage

**Comment by jothi-prasath** [comment]
github pages is designed for hosting static websites. But this site is dynamic which uses python as backend

**Comment by MubarakNative** [comment]
Yes, github pages is for static webpages, if you allow me to contribute this project i try to further improve it

**Comment by jothi-prasath** [comment]
yes, you can. make a pull request

**Comment by MubarakNative** [comment]
Thank you bro!
